server:
  port: 5000
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
          - id: composite
            uri: http://localhost:8080
            predicates:
              - Path=/api/v1/composite

          - id: schools
            uri: http://localhost:8081
            predicates:
              - Path=/api/v1/schools/**

          - id: students
            uri: http://localhost:8082
            predicates:
              - Path=/api/v1/students/**